version: '3.9'

services:
  rentx_postgres: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: rentx-db-postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres

  rentx_redis:
    container_name: rentx-db-redis
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379

  rentx_mongo:
    image: mongo
    container_name: rentx-db-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_NAME}
    ports:
      - ${MONGO_PORT}:27017

  # app:
  #   build: .
  #   container_name: rentx
  #   restart: always
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  #     - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - rentx_postgres
  #     - rentx_redis
  #     - rentx_mongo
  #   depends_on:
  #     - rentx_postgres
  #     - rentx_redis
  #     - rentx_mongo

volumes:
  pgdata:
    driver: local
